Repository JeromeLin/zarm-web, pull requests merged in 2020-03, with the labels that each got.

#222 fix: get correct visible from state or props
  components/dropdown/Dropdown.tsx
Labels: PR: unreviewed, bug

#223 chore: update drawer image url
  components/drawer/style/component.scss
  components/style/images/tab-first@2x.png
Labels: PR: unreviewed, chore

#225 Message & Notification 组件更新
  components/notification/StackItem.tsx
  components/notification/__tests__/stackitem.test.jsx
Labels: PR: unreviewed
