Repository JeromeLin/zarm-web, pull requests merged in 2020-05, with the labels that each got.

#233 fix: fix textarea value prop control
  components/input/Textarea.tsx
Labels: PR: unreviewed, bug

#236 chore: update change drawer close-btn picture to style
  components/drawer/style/component.scss
  components/style/images/tab-first@2x.png
Labels: PR: unreviewed, chore

#234 fix: update menu dropdown popper position error
  components/dropdown/Dropdown.tsx
  components/dropdown/demo.md
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/menu/style/inline-mode.scss
  site/pages/Components/style.scss
  site/styles/pages/dropdown.scss
Labels: bug

#237 chore: update Drawer Close Btn`s Style
  components/drawer/Drawer.tsx
  components/drawer/style/component.scss
Labels: PR: unreviewed, chore
